android: add German translations
simplex-chat/simplex-chat pull request #1079
Opened 2022-09-20 17:15 UTC by epoberezkin

2022-09-21 10:59 UTC, epoberezkin commented on apps/android/app/src/main/res/values-de/strings.xml
> +  <string name="sender_you_pronoun">Du</string>
Maybe, "Sie"?

Or is it common to use "Du" in the apps? In Russian translations we use the equivalent of "Sie"

2022-09-21 11:01 UTC, epoberezkin commented on apps/android/app/src/main/res/values-de/strings.xml
> +  <string name="description_you_shared_one_time_link">Du hast einen One-Time Link geteilt</string>
interesting that you decided not to translate "One-time link".

2022-09-21 11:02 UTC, epoberezkin commented on apps/android/app/src/main/res/values-de/strings.xml
> +  <string name="description_via_contact_address_link_incognito">Über einen Inkognito-Kontaktadressen Link</string>
this is probably incorrect, in this case not the contact address link is incognito, but the user is. So "incognito" is a mode of connection here, not the property of the link

2022-09-21 11:05 UTC, epoberezkin commented on apps/android/app/src/main/res/values-de/strings.xml
>    <string name="invalid_connection_link">Invalid connection link</string>
skipped

2022-09-21 11:08 UTC, epoberezkin commented on apps/android/app/src/main/res/values-de/strings.xml
> +  <string name="periodic_notifications_desc">Die App holt regelmäßig neue Benachrichtigungen ab — dies benötigt ein paar Prozent Akkuleistung am Tag. Die App nutzt keine Push-Benachrichtigungen — es
I think it's better to say the app fetches "messages", not "notifications"

2022-09-23 09:07 UTC, Nisutec requested changes
Hello,
I have checked the translation and have found some problems / wrong translations.

In my opinion the following translations are better translated into German:
``` xml
<!-- PendingContactConnection - ChatModel.kt -->
<string name="description_you_shared_one_time_link">Sie haben einen Einmal-Link geteilt</string>
<string name="description_you_shared_one_time_link_incognito">Sie haben Inkognito einen Einmal-Link geteilt</string>
<string name="description_via_one_time_link">Über einen Einmal-Link</string>
<string name="description_via_one_time_link_incognito">Inkognito über einen Einmal-Link</string>

<!-- API Error Responses - SimpleXAPI.kt -->
<string name="connection_timeout">Verbindungszeitüberschreitung</string>
<string name="connection_error">Verbindungsfehler</string>
<string name="network_error_desc">Bitte überprüfen Sie Ihre Netzwerkverbindung und versuchen Sie es erneut.</string>
<string name="error_sending_message">Fehler beim Senden der Nachricht</string>
<string name="error_adding_members">Fehler beim Hinzufügen von Mitgliedern</string>
<string name="error_joining_group">Fehler beim Beitritt der Gruppe</string>
<string name="cannot_receive_file">Datei kann nicht empfangen werden</string>
<string name="sender_cancelled_file_transfer">Der Absender hat die Dateiübertragung abgebrochen.</string>
<string name="error_receiving_file">Fehler beim Empfangen der Datei</string>
<string name="error_creating_address">Fehler beim Erstellen der Adresse</string>
<string name="error_accepting_contact_request">Fehler beim Akzeptieren der Kontaktanfrage</string>
<string name="sender_may_have_deleted_the_connection_request">Der Absender hat möglicherweise die Verbindungsanfrage gelöscht.</string>

<!-- ChatListView.kt -->
<string name="tap_to_start_new_chat">Tippen Sie um einen neuen Chat zu starten</string>
<string name="chat_with_developers">Chatten Sie mit den Entwicklern</string>
<string name="you_have_no_chats">Sie haben keine Chats</string>

<!-- NewChatSheet -->
<string name="share_one_time_link">Erstellen Sie einen einmaligen Einladungslink</string>
<string name="connect_via_link_or_qr">Per Link / QR-Code verbinden</string>

 <!-- Actions - ChatListNavLinkView.kt -->
<string name="mute_chat">Stummschalten</string>
<string name="unmute_chat">Stummschaltung aufheben</string>

<!-- PasteToConnect.kt -->
<string name="connect_button">Verbinden</string>
<string name="paste_button">Einfügen</string>

<!-- CreateLinkView.kt -->
<string name="one_time_link">Einmaliger Einladungslink</string>
<string name="your_contact_address">Ihre Kontaktadresse</string>

<!-- Default themes -->
<string name="theme_light">Hell</string>
```

And I have found one problem at line 53 behind </string> close tag. There is text behind the close tag.

2022-09-23 16:18 UTC, mlanp commented
@Nisutec:
Thank you for your valuable support. I added your translations and corrections. The push will be done this night.
You have to know, that the German translations are an ongoing and dynamic process at the moment. Therefore some of the strings are not or wrong translated yet. The plan is to finish this process with the release of v4.

2022-09-23 20:38 UTC, Nisutec commented
If you need again help on translating or reviewing feel free to mention me.

2022-09-23 21:57 UTC, merged