Update macOS app icon to comply with HIG
simplex-chat/simplex-chat pull request #3815
Opened 2024-02-16 21:46 UTC by lx-is

<p>Before</p>
<img alt="before" height="128px" src="https://github.com/simplex-chat/simplex-chat/assets/140852203/de38a410-64cf-4067-bac1-dc68cfdfaf43">
<br><br>
<p>After</p>
<img alt="after" height="128px" src="https://github.com/simplex-chat/simplex-chat/assets/140852203/deb6dcfe-d256-40aa-8c67-c7c973a3d747">
<br><br>
<span>-------</span>
<ul>
<li>Complies with Apple's <a href="https://developer.apple.com/design/human-interface-guidelines/app-icons">App Icon Guidelines</a>, including all "1x" and "2x" <a href="https://developer.apple.com/design/human-interface-guidelines/app-icons#macOS-app-icon-sizes">icon sizes</a> (the current icon does not).</li>
<li>Admittedly, I have not tested if this causes any build errors. I skimmed through the applicable sections of the code base and from my understanding only the icns file needs updating.</li>
</ul>

2024-02-24 13:46 UTC, epoberezkin commented
Thanks a lot - it's better indeed, as dragging transparent icon is hard :)

We do need some volume in this case though, so that the shade is a bit gray in the bottom and white on top?

2024-02-24 13:52 UTC, epoberezkin requested changes
see the comment ^^

2024-02-24 18:08 UTC, lx-is commented
Updated 

<img width="85" alt="updated icon" src="https://github.com/simplex-chat/simplex-chat/assets/140852203/00e807c7-2fcb-46ea-b68f-7d53e78d877b">

2024-03-12 13:49 UTC, kimg45 commented
Looks great!

2026-09-06 00:31 UTC, closed without merging